Backend: Vivado
ClockPeriod: 5
HLSConfig:
  LayerName:
    conv2d:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    conv2d_1:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    conv2d_1_relu:
      Precision:
        result: fixed<16,6>
      Trace: false
    conv2d_2:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    conv2d_2_relu:
      Precision:
        result: fixed<16,6>
      Trace: false
    conv2d_input:
      Precision:
        result: fixed<16,6>
      Trace: false
    conv2d_relu:
      Precision:
        result: fixed<16,6>
      Trace: false
    max_pooling2d:
      Precision:
        result: fixed<16,6>
      Trace: false
    up_sampling2d:
      Precision:
        result: fixed<16,6>
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision: fixed<16,6>
    ReuseFactor: 4
    Strategy: Latency
    TraceOutput: false
IOType: io_stream
InputData: null
KerasModel: !keras_model 'my-hls-test/keras_model.h5'
OutputDir: my-hls-test
OutputPredictions: null
Part: xc7z020clg400-1
ProjectName: myproject
Stamp: 2C7abaDb
Version: 1.0.0
